entrada1 = input()
entrada2 = input()
separa_ent1 = entrada1.split()
separa_ent2 = entrada2.split()
cod1 = int(separa_ent1[0])
qt1 = int(separa_ent1[1])
vl1 = float(separa_ent1[2])
cod2 = int(separa_ent2[0])
qt2 = int(separa_ent2[1])
vl2 = float(separa_ent2[2])
total = (qt1 * vl1 + qt2 * vl2)
print ("VALOR A PAGAR: R$ %.2f" % total)
