entrada = input()
separa_ent = entrada.split()
A = float(separa_ent[0])
B = float(separa_ent[1])
C = float(separa_ent[2])
TRIANGULO = ((A * C)/2)
CIRCULO = (3.14159 * (C**2))
TRAPEZIO = (((A + B) * C)/2)
QUADRADO = (B**2)
RETANGULO = (A * B)
print ("TRIANGULO: %.3f" % TRIANGULO)
print("CIRCULO: %.3f" % CIRCULO)
print ("TRAPEZIO: %.3f" % TRAPEZIO)
print ("QUADRADO: %.3f" % QUADRADO)
print ("RETANGULO: %.3f" % RETANGULO)
