entrada = input()
separa_ent = entrada.split()
a = int(separa_ent[0])
b = int(separa_ent[1])
c = int(separa_ent[2])
MaiorAB = ((a + b + abs(a - b))/2)
MaiorABC = ((MaiorAB + c + abs(MaiorAB - c))/2) 
print ("%d eh o maior" % MaiorABC)
