entrada1 = input()
entrada2 = input()
separa_ent1 = entrada1.split()
separa_ent2 = entrada2.split()
x1 = float(separa_ent1[0])
y1 = float(separa_ent1[1])
x2 = float(separa_ent2[0])
y2 = float(separa_ent2[1])
dist = ((((x2 - x1)**2) + ((y2-y1)**2))**(1/2))
print("%.4f" % dist)
