idade_tt_dias = int(input())
quantd_anos = int(idade_tt_dias/365)
resto_anos = int(idade_tt_dias%365)
quantd_mes = int(resto_anos/30)
resto_mes = int(resto_anos%30)
quantd_dias = int(resto_mes)
print("%d ano(s)" % quantd_anos)
print("%d mes(es)" % quantd_mes)
print("%d dia(s)" % quantd_dias)
